[tools]
node = "24.14.0"
pnpm = "11.5.1"

[tasks.build]
description = "Build the application"
run = "pnpm exec vite build"

[tasks.check]
description = "Run all static checks"
depends = ["check:*"]

[tasks."check:format"]
description = "Check formatting"
run = "pnpm exec prettier --check ."

[tasks."check:typecheck"]
description = "Run type checking"
run = "pnpm exec svelte-check --tsconfig ./tsconfig.json"

[tasks.dev]
description = "Run the local development server"
run = "pnpm exec vite dev"

[tasks.format]
description = "Fix formatting issues"
run = "pnpm exec prettier --write ."

[tasks.storybook]
description = "Start the storybook dev server"
run = "pnpm exec storybook dev -p 6006"

[tasks."test:unit"]
description = "Run unit tests"
run = "pnpm exec vitest"

[tasks.test]
description = "Run all tests"
depends = ["test:*"]

[deps.pnpm]
auto = true 

[deps.sveltekit-sync]
auto = true
outputs = [".svelte-kit"]
run = "pnpm exec svelte-kit sync"
depends = ["pnpm"]
description = "Generate SvelteKit type definitions"
